timeout: 600s

images:
  - "gcr.io/$PROJECT_ID/population-graph-app:$COMMIT_SHA"

steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/population-graph-app:$COMMIT_SHA",
        ".",
        "--build-arg",
        "RESAS_API_KEY=${_RESAS_API_KEY}",
      ]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/population-graph-app:$COMMIT_SHA"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "population-graph-app"
      - "--allow-unauthenticated"
      - "--image"
      - "gcr.io/$PROJECT_ID/population-graph-app:$COMMIT_SHA"
      - "--region"
      - "asia-northeast1"
      - "--min-instances"
      - "0"
      - "--max-instances"
      - "1"
