name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  playwright:
    if: github.event.pull_request.draft == false
    name: "Playwright Tests - ${{ matrix.project }} - Shard ${{ matrix.shard }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: ["Desktop Chrome", "Mobile Chrome", "Mobile Safari"]
        shard: [1/10, 2/10, 3/10, 4/10, 5/10, 6/10, 7/10, 8/10, 9/10, 10/10]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      - name: Install dependencies
        run: yarn install

      - name: Install browsers
        run: npx playwright install --with-deps

      - name: Run your tests
        run: yarn test:e2e --project=${{ matrix.project }} --shard=${{ matrix.shard }}
