name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  lint:
    if: github.event.pull_request.draft == false
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.17.1]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install Dependencies
        shell: bash
        run: yarn install

      - name: Type Check
        run: yarn type-check

      - name: Lint
        run: yarn lint:check

      - name: Lint CSS
        run: yarn lint-css:check

      - name: Format
        run: yarn format:check

      - name: Build
        run: yarn build
